### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ashish3805** [ashish3805/Infinite-Image-Loader#5]
- [x] 1.completed using screenInit() return req_no
- [x] 2. based on req_no. extend screenInit() or make new function to place placeholders of size relative to Height and Width of image. Also put dummy graphic init see http://tobiasahlin.com/spinkit/
- [x] 3. find a way to retrieve the image(URL given) and track its status.
- [x] 4. if image is loaded place the image by replacing the dummy graphic.
- [x] 5. Completed using addScreen()
- [x] 6. Completed

**Comment by ashish3805** [comment]
Done!
